my_blog/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

app_name='posts'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include('posts.urls',namespace='posts')),

]

if settings.DEBUG:
	urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from .  import views

urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^(?P<id>\d+)/$',views.detail,name="detail"),

    #urls for the navigation bar
    url(r'^register/$',views.RegistrationView.as_view(), name='registration'),
    url(r'^login/$',views.LoginView.as_view(), name='login'),
	url(r'^logout$',views.logout_view,name="logout"),
	url(r'^add/$', views.PostCreate.as_view(), name='addpost'),

	#like-button
	url(r'^like_category/$', views.like_category, name='like_category'),

    url(r'^unlike_category/$', views.unlike_category, name='unlike_category'),

    url(r'^posts/(?P<id>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),

    #url to the detailed user information
    url(r'^user_info/$', views.user_info, name='user_info'),

    url(r'^user_info/edit/$', views.ProfileInfoUpdate, name='user_info_edit'),
    
    url(r'^create_post/$', views.post_create, name='create_post'),
    url(r'^post_update/(?P<id>\d+)/$', views.post_update, name='edit_post'),
    url(r'^post_delete/(?P<id>\d+)/$', views.post_delete, name='delete_post'),



]

posts/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models
from django.shortcuts import redirect
# Create your models here.


class Post(models.Model):
	title=models.CharField(max_length=120)
	image=models.FileField(null=True,blank=True)
	content=models.TextField()
	updated=models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp=models.DateTimeField(auto_now=False, auto_now_add=True)
	likes=models.IntegerField(default=0)
	dislikes=models.IntegerField(default=0)
	created_user=models.CharField(max_length=120,blank=True)

	def get_absolute_url(self):
		return reverse('posts:detail',kwargs={'id':self.id})


	def __str__(self):
		return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now=False, auto_now_add=True)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

class User_Detailed_Info(models.Model):
	name=models.CharField(max_length=120)
	email = models.EmailField(max_length=70,blank=True)
	phone_no=models.IntegerField(default=0,blank=True)
	about=models.TextField(blank=True)
	profile_pic=models.FileField(blank=True)



	def __str__(self):
		return self.name

posts/forms.py
from django import forms
from django.contrib.auth.models import User
from posts.models import Post,Comment,User_Detailed_Info

class PostForm(forms.ModelForm):
	class Meta:
		model=Post
		fields=["title","image","content"]


class RegistrationForm(forms.ModelForm):
	password=forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model=User
		fields=['username','email','password']

class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField( widget = forms.PasswordInput)

	class Meta:
		model=User
		fields=['username','password']

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['text',]

class DetailedUserForm(forms.ModelForm):
	email=forms.CharField(widget=forms.EmailInput)

	class Meta:
		model=User_Detailed_Info
		fields = [ 'email','profile_pic','phone_no','about',]

posts/views.py
from django.http import HttpResponse 
from django.shortcuts import render,get_object_or_404,redirect
from django.core.urlresolvers import reverse
from posts.models import Post,Comment,User_Detailed_Info
from posts.forms import PostForm,CommentForm,DetailedUserForm
from django.views.generic import View
from posts.forms import RegistrationForm,LoginForm
from django.contrib.auth import authenticate,login
from django.contrib.auth import logout
from django.views.generic.edit import CreateView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages


# Create your views here.
def post_create(request):
	form=PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance=form.save(commit=False)
		instance.created_user=request.user
		instance.save()
	context={ "form":form }
	return render(request,"my_blog/post_create.html",context)

def post_update(request,id=None):
	instance=get_object_or_404(Post,id=id)
	if instance.created_user != request.user.username :
		messages.success(request, "Post owned by another user, You are having read permission only")
		return render(request,"my_blog/denied.html",{})
	else :	
		form=PostForm(request.POST or None,request.FILES or None,instance=instance)
		if form.is_valid():
			instance=form.save(commit=False)
			instance.save()
		context={ "form":form,
				  "instance":instance }

		return render(request,"my_blog/post_create.html",context)

def post_delete(request,id):
	form=PostForm(request.POST or None)
	instance=get_object_or_404(Post,id=id)
	if instance.created_user != request.user.username :
		messages.success(request, "Post owned by another user, You are having read permission only")
		return render(request,"my_blog/denied.html",{})

	else:
		instance.delete()
		return redirect("posts:index")

def index(request):
	lists=Post.objects.all().order_by("-timestamp")
	return render(request,"my_blog/index.html",{'lists':lists})


def detail(request,id):
	lists=Post.objects.get(pk=id)
	return render(request,"my_blog/detail.html",{'lists':lists,})



class RegistrationView(View):
	form_class=RegistrationForm
	template_name='my_blog/user_login_form.html'


	def get(self,request):
		form=self.form_class(None)
		return render(request,self.template_name,{'form':form})

	def post(self,request):
		form=self.form_class(request.POST)

		if form.is_valid():

			user=form.save(commit=False)

			#cleaned (normalized) data
			username =form.cleaned_data['username']
			password =form.cleaned_data['password']
			email=form.cleaned_data['email']
			user.set_password(password)
			user.save()

			#saving the basic data to another model for user datails
			temp_user_details=User_Detailed_Info()
			temp_user_details.name=username
			temp_user_details.email=email
			temp_user_details.save()

			messages.success(request,"User successfully created now logIn please")
		return render(request,self.template_name,{'form':form,})


class LoginView(View):
	form_class=LoginForm
	template_name='my_blog/user_login_form.html'


	def get(self,request):
		form=self.form_class(None)
		return render(request,self.template_name,{'form':form})

	def post(self,request):
		form=self.form_class(request.POST)

		if form.is_valid():


			#cleaned (normalized) data
			username =form.cleaned_data['username']
			password =form.cleaned_data['password']

	

			#authentication

			user=authenticate(username=username,password=password)

			if user:
				pass
			else:
				messages.success(request,"Wrong password or username")
				

			if user is not None:
				if user.is_active:
						login(request,user)
						lists=Post.objects.all().order_by("-timestamp")
						return render(request,'my_blog/index.html',{"user":user,"lists":lists})

		return render(request,self.template_name,{'form':form})


#-----log-out

def logout_view(request):
    logout(request)
    return redirect('posts:index')


# for creating new posts

class PostCreate(CreateView):
	model=Post
	template_name='my_blog/post_form.html'
	fields=['title','image','content']


# likes for the post
def like_category(request):

    post_id = None
    if request.method == 'GET':
        post_id = request.GET['like_id']

    likes = 0
    if post_id:
        post = Post.objects.get(id=int(post_id))
        if post:
            likes = post.likes + 1
            post.likes =  likes
            post.save()

    return HttpResponse(likes)

def unlike_category(request):

    post_id = None
    if request.method == 'GET':
        post_id = request.GET['dislike_id']

    unlikes = 0
    if post_id:
        post = Post.objects.get(id=int(post_id))
        if post:
            unlikes = post.dislikes + 1
            post.dislikes =  unlikes
            post.save()

    return HttpResponse(unlikes)



def add_comment_to_post(request, id):
    post = get_object_or_404(Post, pk=id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author=request.user
            comment.save()
            return redirect('posts:detail', id=post.id)
    else:
        form = CommentForm()
    return render(request, 'my_blog/add_comment_to_post.html', {'form': form})

#to see the detailed user information

def user_info(request):
	current_user=User_Detailed_Info.objects.get(name=request.user)
	user_posts=Post.objects.filter(created_user=request.user.username)
	return render(request,'my_blog/user_detailed_info.html',{"current_user":current_user,"user_posts":user_posts})


def ProfileInfoUpdate(request):
	instance=User_Detailed_Info.objects.get(name=request.user)
	form=DetailedUserForm(request.POST or None,request.FILES or None,instance=instance)
	if form.is_valid():
		instance=form.save(commit=False)
		instance.save()
	context={ "form":form,
			  "instance":instance }

	return render(request,"my_blog/post_create.html",context)

posts/templates/my_blog/add_comment_to_post.html
{% extends 'my_blog/base.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

posts/templates/my_blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>Posts</title>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js">
   </script>
  <script src="{% static 'js/main.js' %}"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">



  <link rel="stylesheet" href="{% static 'css/blog.css' %}">


</script>

</head>
<body>
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="{% url 'posts:index'%}">SocialMediaApp</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	    	 <ul class="nav navbar-nav navbar-left">
	        <li><a href="https://github.com/Ananthu/E-commerceApp-using-python-library">SourceCode</a></li>
	        </ul>
	      
	      {% if request.user.is_authenticated %}
	       	<ul class="nav navbar-nav navbar-right">
	       	<p class="navbar-text">Logged in as: {{user}}</p> 
	      	<li><a href="{% url 'posts:user_info' %}">UserInfo</a></li>	       	
	      	<li><a href="{% url 'posts:logout' %}">LogOut</a></li>
	        <li><a href="{% url 'posts:create_post' %}">NewPost</a></li>
	        </ul>

	      {% else %}
	      	<ul class="nav navbar-nav navbar-right">
	        <li><a href="{% url 'posts:registration' %}">Register</a></li>
	        <li><a href="{% url 'posts:login' %}">Login</a></li>
	        </ul>
	       {% endif %}
	      
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

	{% if messages %}
	<ul class="messages">
	    {% for message in messages %}
	    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
	    {% endfor %}
	</ul>
	{% endif %}
	
	<div class="container">

		{% block content %}{% endblock content%}
	</div>
</body>
</html>

posts/templates/my_blog/base_model_for_all_forms.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors }}</span>
			
		</div>
		<label class="control-label col-sm-2">{{ field.label_tag}}</label>
		<div class="col-sm-10">{{ field }}</div>
	</div>
{% endfor %}

posts/templates/my_blog/denied.html
{% extends 'my_blog/base.html' %}

{% block content %}	

	<h1> The post owned by another user. You can not channge It</h1>

{% endblock content %}	

posts/templates/my_blog/detail.html
{% extends 'my_blog/base.html' %}


{% block content %}

<h3><a href="{% url 'posts:index'  %}">Home</a></h3>
<h3><a href="{% url 'posts:edit_post' id=lists.id %}">Edit</a></h3>
<h3><a href="{% url 'posts:delete_post' id=lists.id %}">Delete</a></h3>

<div class="col-sm-8 col-sm-offset-2">
	{% if lists.image %}
		<img src="{{ lists.image.url }}" class="img-responsive">
	{% endif %}
	<h3>{{ lists.title }}</h3>
	{{ lists.content|linebreaks }}
	{{ lists.updated }}<br/>
	<h4>PostCreated By ->{{ lists.created_user }}</h4> <br/>


{% if lists.comment_set.all %}
	<h3>Available Comments</h3>
	{% for comment in lists.comment_set.all %}
	    <div class="comment">
	        
	        <strong><h4>Commented By->{{ comment.author }}</h4></strong><span><div class="date">{{ comment.created_date }}</div></span>
	        <h5>{{ comment.text|linebreaks }}</h5>
	    </div>
	    <br>
	{% empty %}
	    <p>No comments here yet :(</p>
	{% endfor %}
{% else %}
<h3>No Comments To display</h3>
{% endif %}

<a class="btn btn-default" href="{% url 'posts:add_comment_to_post' id=lists.id %}">Add Comment</a>
</div>


{% endblock content %}
 

posts/templates/my_blog/index.html
{% extends 'my_blog/base.html' %}

{% block content %}	
{% if lists %}
<div class="col-sm-10 col-sm-offset-1">
	{% for lt in lists %}
		<div class="row">
		  <div class="col-sm-12">
		    <div class="thumbnail">
		      {% if lt.image%}
		      <!img src="{{ lt.image.url }}" class="img-responsive">
		      {% endif %}
		      <img src="{{ lt.image.url }}" alt="...">
		      <div class="caption">
		        <h3><a href="{% url 'posts:detail' lt.id %}">{{ lt.title}}</a><small>  {{ lt.timestamp|timesince }} ago</small></h3>
		        <p>{{ lt.content|linebreaks|truncatechars:120 }}</p>
		        <p><a href="{% url 'posts:detail' lt.id %}" class="btn btn-primary" role="button">View</a></p>
				        <button  data-like-id="{{ lt.id }}" class="btn btn-primary glyphicon glyphicon-thumbs-up likes" type="button">
				        Like {% if lt.likes > 0 %} {{lt.likes}} {% endif %}
				        </button>	  
				     	<button id="dislike{{ lt.id }}" data-dislike-id="{{ lt.id }}" class="btn btn-primary glyphicon glyphicon-thumbs-down dislikes" type="button">
				        DisLikes {% if lt.dislikes > 0 %} {{lt.dislikes}} {% endif %}
				        </button>    
				</div>
		    </div>
		  </div>
		</div>
		{% endfor %}
</div>
{% else %}
<h1> No Posts to display </h1>
{% endif %}
{% endblock %}

posts/templates/my_blog/post_create.html
{% extends "my_blog/base.html" %}


{% block content%}
	<h3><a href="{% url 'posts:index' %}">Home</a></h3>
	<div class="col-sm-8 col-sm-offset-2"">
		<form method="POST" action="" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form.as_p}}
			<input type="submit" Value="Done">
		</form>
	</div>
{% endblock %}

posts/templates/my_blog/post_form.html
{% extends 'my_blog/base.html' %}


{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<div class="container center_div">
	
	<div class="row">

		<div class="col-sm-6 col-md-10">
			<div class="panel panel-default">
				<div class="panel-body">

					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'my_blog/base_model_for_all_forms.html' %}
						<div class="form-group"></div>
							<div class="col-sm-offset-4 col-sm-10">
							<button type="submit" class="btn btn-success">Submit</button>
								
							</div>
					</form>
						
				</div>
			
			</div>
			
		</div>
		
	</div>
</div>
{% endblock %}

posts/templates/my_blog/user_detailed_info.html
{% extends 'my_blog/base.html' %}

{% block content %}	
<div class="col-sm-offset-0">
	<h3><a href="{% url 'posts:user_info_edit' %}">Edit Info</a></h3>
	<h3><a href="{% url 'posts:index' %}">Home</a></h3>
</div>
<div class="col-sm-offset-2">
	<h2>User Name:{{current_user.name}}</h2><span>email:{{ current_user.email }}</span>
	{% if current_user.profile_pic %}
		<div >
			<img src="{{ current_user.profile_pic.url }}" height="400" width="400">
		</div>
	{% endif%}
	{% if current_user.phone_no %}
		<div >
			<h3>Contact no :{{ current_user.phone_no }}</h3>
		</div>
	{% endif%}
	{%if current_user.about %}
		<div >
			<h2>About Me</h2>
			<p>{{ current_user.about }}</p>
		</div>
	{% endif%}

	
	

	<h2>User Posts</h2>
	{% for post in user_posts %}
		<h2><a href="{% url 'posts:detail' post.id %}">{{ post.title}}</a></h2>
	{% endfor %}
</div>


{% endblock %}

posts/templates/my_blog/user_login_form.html
{% extends 'my_blog/base.html' %}


{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<div class="container center_div">
	
	<div class="row">

		<div class="col-sm-6 col-md-10">
			<div class="panel panel-default">
				<div class="panel-body">

					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'my_blog/base_model_for_all_forms.html' %}
						<div class="form-group"></div>
							<div class="col-sm-offset-4 col-sm-10">
							<button type="submit" class="btn btn-success">Submit</button>
								
							</div>
					</form>
						
				</div>
			
			</div>
			
		</div>
		
	</div>
</div>
{% endblock %}

posts/templates/my_blog/user_registration_form.html
{% extends 'my_blog/base.html' %}


{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<div class="container center_div">
	
	<div class="row">

		<div class="col-sm-6 col-md-10">
			<div class="panel panel-default">
				<div class="panel-body">

					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'my_blog/base_model_for_all_forms.html' %}
						<div class="form-group"></div>
							<div class="col-sm-offset-4 col-sm-10">
							<button type="submit" class="btn btn-success">Submit</button>
								
							</div>
					</form>
						
				</div>
			
			</div>
			
		</div>
		
	</div>
</div>
{% endblock %}